name: weather_app
description: "It's funny weather"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed: ^2.4.6
  dio: ^5.4.0
  json_annotation: ^4.8.1
  geolocator: ^13.0.1
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true


